import { Dispatch, SetStateAction, useMemo } from 'react';
import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAppSettings } from '../../application/AppSettingsContext';
import { formatMeasurementDate } from '../../domain/bodyProgress';
import { ProgressPhoto } from '../../domain/types';
import { ThemeColors } from '../../ui/theme';

export type BodyProfileDraft = { heightCm: string; age: string; sex: 'male' | 'female' };
export type BodyMeasurementDraft = { weightKg: string; bodyFatPct: string; musclePct: string; bonePct: string; waterPct: string };

export function BodyProfileModal({ close, draft, save, setDraft }: { close: () => void; draft: BodyProfileDraft | null; save: () => void; setDraft: Dispatch<SetStateAction<BodyProfileDraft | null>> }) {
  const { colors, preferences } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]);
  if (!draft) return null;
  return <Modal transparent animationType="slide" visible onRequestClose={close}><View style={s.scrim}><View style={s.card}><Text style={s.title}>Datos personales</Text><TextInput keyboardType="decimal-pad" placeholder={`Altura en ${preferences.bodyUnit}`} placeholderTextColor={colors.textSubtle} style={s.input} value={draft.heightCm} onChangeText={(heightCm) => setDraft((current) => current ? { ...current, heightCm } : current)} /><TextInput keyboardType="number-pad" placeholder="Edad" placeholderTextColor={colors.textSubtle} style={s.input} value={draft.age} onChangeText={(age) => setDraft((current) => current ? { ...current, age } : current)} /><Text style={s.label}>Sexo para rangos corporales</Text><View style={s.segments}><Segment active={draft.sex === 'male'} label="Hombre" onPress={() => setDraft((current) => current ? { ...current, sex: 'male' } : current)} /><Segment active={draft.sex === 'female'} label="Mujer" onPress={() => setDraft((current) => current ? { ...current, sex: 'female' } : current)} /></View><Actions close={close} save={save} /></View></View></Modal>;
}

export function BodyMeasurementModal({ close, draft, save, setDraft }: { close: () => void; draft: BodyMeasurementDraft | null; save: () => void; setDraft: Dispatch<SetStateAction<BodyMeasurementDraft | null>> }) {
  const { colors, preferences } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]);
  if (!draft) return null;
  const update = (key: keyof BodyMeasurementDraft) => (value: string) => setDraft((current) => current ? { ...current, [key]: value } : current);
  return <Modal transparent animationType="slide" visible onRequestClose={close}><View style={s.scrim}><ScrollView style={s.editorCard} contentContainerStyle={s.editorContent}><Text style={s.title}>Nueva medicion</Text><Text style={s.muted}>La fecha se guarda automaticamente con el momento actual.</Text><MeasurementInput label={`Peso ${preferences.weightUnit}`} value={draft.weightKg} onChange={update('weightKg')} /><MeasurementInput label="Grasa %" value={draft.bodyFatPct} onChange={update('bodyFatPct')} /><MeasurementInput label="Musculo %" value={draft.musclePct} onChange={update('musclePct')} /><MeasurementInput label="Hueso %" value={draft.bonePct} onChange={update('bonePct')} /><MeasurementInput label="Agua %" value={draft.waterPct} onChange={update('waterPct')} /><Actions close={close} save={save} /></ScrollView></View></Modal>;
}

export function ProgressPhotoViewer({ close, deletePhoto, photo, saveToGallery }: { close: () => void; deletePhoto: (photoId: string) => void; photo: ProgressPhoto | null; saveToGallery: (photo: ProgressPhoto) => void }) {
  const insets = useSafeAreaInsets(); const { colors } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]);
  if (!photo) return null;
  return <Modal transparent animationType="fade" visible onRequestClose={close}><View style={[s.viewerScrim, { paddingTop: insets.top + 78, paddingBottom: Math.max(insets.bottom, 18) + 98 }]}><View style={[s.viewerTopBar, { top: insets.top + 12 }]}><Pressable accessibilityRole="button" style={s.viewerButton} onPress={close}><Text style={s.viewerButtonText}>Cerrar</Text></Pressable><Text style={s.viewerDate}>{formatMeasurementDate(photo.capturedAt)}</Text></View><Image source={{ uri: photo.uri }} style={s.viewerImage} resizeMode="contain" /><View style={[s.viewerActions, { bottom: Math.max(insets.bottom, 18) + 14 }]}><Pressable accessibilityRole="button" style={s.saveButton} onPress={() => saveToGallery(photo)}><Text style={s.saveText}>Guardar</Text></Pressable><Pressable accessibilityRole="button" style={s.deleteButton} onPress={() => { deletePhoto(photo.id); close(); }}><Text style={s.deleteText}>Eliminar</Text></Pressable></View></View></Modal>;
}

function MeasurementInput({ label, onChange, value }: { label: string; onChange: (value: string) => void; value: string }) { const { colors } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]); return <View><Text style={s.label}>{label}</Text><TextInput keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.textSubtle} style={s.input} value={value} onChangeText={onChange} /></View>; }
function Segment({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { const { colors } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]); return <Pressable accessibilityRole="button" style={[s.segment, active && s.segmentActive]} onPress={onPress}><Text style={[s.segmentText, active && s.segmentTextActive]}>{label}</Text></Pressable>; }
function Actions({ close, save }: { close: () => void; save: () => void }) { const { colors } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]); return <View style={s.actions}><Pressable accessibilityRole="button" style={s.secondary} onPress={close}><Text style={s.secondaryText}>Cancelar</Text></Pressable><Pressable accessibilityRole="button" style={s.primary} onPress={save}><Text style={s.primaryText}>Guardar</Text></Pressable></View>; }

function createStyles(c: ThemeColors) { return StyleSheet.create({ scrim:{flex:1,backgroundColor:c.scrim,alignItems:'center',justifyContent:'center',padding:20},card:{width:'100%',maxWidth:520,borderRadius:18,backgroundColor:c.surface,padding:20,gap:14},editorCard:{width:'100%',maxWidth:520,maxHeight:'86%',borderRadius:18,backgroundColor:c.surface},editorContent:{padding:20,gap:14},title:{color:c.text,fontSize:24,fontWeight:'900'},label:{color:c.text,fontSize:13,fontWeight:'800',marginBottom:7},muted:{color:c.textMuted,fontSize:13,lineHeight:19},input:{minHeight:48,borderRadius:12,borderWidth:1,borderColor:c.borderStrong,color:c.text,paddingHorizontal:14,fontSize:15,fontWeight:'700'},segments:{flexDirection:'row',gap:8},segment:{flex:1,minHeight:44,borderRadius:11,backgroundColor:c.surfaceElevated,alignItems:'center',justifyContent:'center'},segmentActive:{backgroundColor:c.primary},segmentText:{color:c.textMuted,fontWeight:'900'},segmentTextActive:{color:c.onPrimary},actions:{flexDirection:'row',gap:10,marginTop:4},secondary:{flex:1,minHeight:48,borderRadius:12,backgroundColor:c.surfaceElevated,alignItems:'center',justifyContent:'center'},secondaryText:{color:c.text,fontWeight:'900'},primary:{flex:1,minHeight:48,borderRadius:12,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},primaryText:{color:c.onPrimary,fontWeight:'900'},viewerScrim:{flex:1,backgroundColor:'#000',alignItems:'center',justifyContent:'center'},viewerTopBar:{position:'absolute',left:18,right:18,zIndex:2,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},viewerButton:{minHeight:42,paddingHorizontal:15,borderRadius:12,backgroundColor:'rgba(255,255,255,0.16)',alignItems:'center',justifyContent:'center'},viewerButtonText:{color:'#fff',fontWeight:'900'},viewerDate:{color:'#fff',fontWeight:'800'},viewerImage:{width:'100%',height:'100%'},viewerActions:{position:'absolute',left:18,right:18,flexDirection:'row',gap:10},saveButton:{flex:1,minHeight:50,borderRadius:12,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},saveText:{color:c.onPrimary,fontWeight:'900'},deleteButton:{flex:1,minHeight:50,borderRadius:12,backgroundColor:c.danger,alignItems:'center',justifyContent:'center'},deleteText:{color:c.onDanger,fontWeight:'900'} }); }
