import { StyleSheet } from 'react-native';
import { resolveLegacyColor, ThemeColors } from './theme';

export function createStyles(theme: ThemeColors) {
  return StyleSheet.create({
  settingsScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  settingsHeader: {
    minHeight: 76,
    paddingHorizontal: 18,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    backgroundColor: theme.background,
  },
  settingsBack: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  settingsTitle: {
    color: theme.text,
    fontSize: 22,
    fontWeight: '900',
  },
  settingsContent: {
    padding: 18,
    gap: 16,
  },
  settingsSection: {
    padding: 18,
    gap: 16,
    borderRadius: 18,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  settingsSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  settingsSectionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.surfaceElevated,
  },
  settingsSectionTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '900',
  },
  themeChoices: {
    flexDirection: 'row',
    gap: 8,
  },
  themeChoice: {
    flex: 1,
    minHeight: 76,
    borderRadius: 14,
    gap: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.border,
  },
  themeChoiceActive: {
    backgroundColor: theme.primary,
    borderColor: theme.primary,
  },
  themeChoiceText: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: '800',
  },
  themeChoiceTextActive: {
    color: theme.onPrimary,
  },
  unitSetting: {
    gap: 8,
  },
  unitOptions: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: 12,
    backgroundColor: theme.surfaceElevated,
  },
  unitOption: {
    flex: 1,
    minHeight: 42,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitOptionActive: {
    backgroundColor: theme.primary,
  },
  unitOptionText: {
    color: theme.textMuted,
    fontWeight: '900',
  },
  unitOptionTextActive: {
    color: theme.onPrimary,
  },
  settingRow: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  settingAction: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 4,
  },
  settingText: {
    flex: 1,
    gap: 3,
  },
  settingLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '800',
  },
  settingDescription: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  settingsFooter: {
    alignItems: 'center',
    gap: 5,
    paddingVertical: 18,
  },
  shell: {
    flex: 1,
    backgroundColor: resolveLegacyColor('#101418', theme),
  },
  gestureRoot: {
    flex: 1,
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: resolveLegacyColor('#101418', theme),
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 12,
  },
  launchLogo: {
    width: 152,
    height: 152,
    borderRadius: 34,
    marginBottom: 4,
  },
  loadingTitle: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 8,
  },
  storageBanner: {
    marginHorizontal: 20,
    marginBottom: 8,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#D84A4A', theme),
    padding: 10,
  },
  storageBannerText: {
    color: resolveLegacyColor('#FFFFFF', theme),
    fontWeight: '900',
    textAlign: 'center',
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 14,
  },
  headerTitle: {
    flex: 1,
  },
  kicker: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  title: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 26,
    fontWeight: '900',
    marginTop: 4,
  },
  content: {
    padding: 20,
  },
  stack: {
    gap: 14,
  },
  hero: {
    backgroundColor: resolveLegacyColor('#1B242B', theme),
    borderRadius: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#2D3A43', theme),
  },
  panel: {
    backgroundColor: resolveLegacyColor('#172027', theme),
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
  },
  workoutCard: {
    backgroundColor: resolveLegacyColor('#EAF2EE', theme),
    borderRadius: 8,
    padding: 18,
    gap: 16,
  },
  sessionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  sectionLabel: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  eyebrow: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  h1: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 32,
    fontWeight: '900',
  },
  h2: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 24,
    fontWeight: '900',
  },
  heroCopy: {
    color: resolveLegacyColor('#BAC6CF', theme),
    fontSize: 16,
    lineHeight: 23,
    marginTop: 8,
    marginBottom: 18,
  },
  panelTitle: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 18,
    fontWeight: '900',
  },
  muted: {
    color: resolveLegacyColor('#9BA8B4', theme),
    fontSize: 13,
    lineHeight: 19,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#7DD3C7', theme),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: resolveLegacyColor('#071313', theme),
    fontWeight: '900',
    fontSize: 15,
  },
  secondaryButton: {
    marginTop: 14,
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#7DD3C7', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontWeight: '900',
    textAlign: 'center',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  actionButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#7DD3C7', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonPrimary: {
    flex: 1,
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#7DD3C7', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactButton: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#7DD3C7', theme),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  compactButtonText: {
    color: resolveLegacyColor('#071313', theme),
    fontWeight: '900',
  },
  endButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#F0B35B', theme),
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  endButtonText: {
    color: resolveLegacyColor('#F0B35B', theme),
    fontSize: 12,
    fontWeight: '900',
  },
  segmented: {
    marginTop: 16,
    backgroundColor: resolveLegacyColor('#0F151A', theme),
    borderRadius: 8,
    flexDirection: 'row',
    padding: 4,
    gap: 4,
  },
  segmentButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeSegment: {
    backgroundColor: resolveLegacyColor('#EAF2EE', theme),
  },
  segmentText: {
    color: resolveLegacyColor('#8F9CA7', theme),
    fontWeight: '900',
  },
  activeSegmentText: {
    color: resolveLegacyColor('#111A1F', theme),
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  sessionStats: {
    flexDirection: 'row',
    gap: 10,
  },
  metric: {
    width: '48%',
    minHeight: 92,
    backgroundColor: resolveLegacyColor('#222D35', theme),
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#31404A', theme),
    justifyContent: 'space-between',
  },
  metricValue: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 24,
    fontWeight: '900',
  },
  metricLabel: {
    color: resolveLegacyColor('#AAB6C1', theme),
    fontSize: 12,
    marginTop: 4,
    fontWeight: '700',
  },
  actualGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  actualInputBox: {
    flex: 1,
    backgroundColor: resolveLegacyColor('#DDE8E3', theme),
    borderRadius: 8,
    padding: 12,
  },
  actualInputLabel: {
    color: resolveLegacyColor('#52606A', theme),
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 8,
  },
  actualInput: {
    color: resolveLegacyColor('#111A1F', theme),
    fontSize: 26,
    fontWeight: '900',
    minHeight: 42,
    padding: 0,
  },
  exerciseName: {
    color: resolveLegacyColor('#111A1F', theme),
    fontSize: 28,
    fontWeight: '900',
  },
  routineNote: {
    color: resolveLegacyColor('#697781', theme),
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 20,
    borderLeftWidth: 3,
    borderLeftColor: resolveLegacyColor('#7DD3C7', theme),
    paddingLeft: 10,
  },
  generalExerciseNote: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  noteAction: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
  },
  noteActionText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  setMeta: {
    color: resolveLegacyColor('#54616B', theme),
    fontSize: 14,
    fontWeight: '800',
  },
  restBox: {
    borderRadius: 8,
    padding: 18,
    backgroundColor: theme.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    alignItems: 'center',
  },
  restLabel: {
    color: theme.warning,
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  restTime: {
    color: theme.text,
    fontSize: 42,
    fontWeight: '900',
    marginTop: 4,
  },
  timerControls: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    width: '100%',
  },
  timerButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerButtonText: {
    color: theme.text,
    fontWeight: '900',
  },
  timerButtonPrimary: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: theme.warning,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerButtonPrimaryText: {
    color: '#16110A',
    fontWeight: '900',
  },
  pinnedTimer: {
    position: 'absolute',
    left: 14,
    right: 14,
    minHeight: 66,
    borderRadius: 8,
    backgroundColor: theme.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pinnedTimerButton: {
    width: 54,
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinnedTimerButtonText: {
    color: theme.text,
    fontWeight: '900',
  },
  pinnedTimerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  pinnedTimerLabel: {
    color: theme.warning,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  pinnedTimerValue: {
    color: theme.text,
    fontSize: 26,
    fontWeight: '900',
  },
  pinnedTimerSkip: {
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: theme.primary,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinnedTimerSkipText: {
    color: theme.onPrimary,
    fontWeight: '900',
  },
  overviewTimer: {
    borderRadius: 8,
    backgroundColor: theme.surfaceElevated,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  overviewTimerLabel: {
    color: theme.warning,
    fontWeight: '900',
    textTransform: 'uppercase',
    fontSize: 12,
  },
  overviewTimerValue: {
    color: theme.text,
    fontSize: 26,
    fontWeight: '900',
  },
  exercisePanel: {
    backgroundColor: resolveLegacyColor('#172027', theme),
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
  },
  overviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  overviewExercise: {
    color: resolveLegacyColor('#D8E1E8', theme),
    fontSize: 20,
    fontWeight: '900',
  },
  currentOverviewExercise: {
    color: resolveLegacyColor('#7DD3C7', theme),
  },
  overviewRest: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 14,
    fontWeight: '800',
    marginTop: 8,
  },
  skipExerciseButton: {
    minHeight: 38,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#26343D', theme),
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipExerciseButtonText: {
    color: resolveLegacyColor('#F0B35B', theme),
    fontWeight: '900',
    fontSize: 12,
  },
  setTableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: resolveLegacyColor('#2B3943', theme),
  },
  setRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: resolveLegacyColor('#24313A', theme),
  },
  currentSetRow: {
    backgroundColor: resolveLegacyColor('#25353A', theme),
  },
  completedSetRow: {
    backgroundColor: resolveLegacyColor('#BDFCA1', theme),
  },
  setColumnSmall: {
    width: 54,
    color: resolveLegacyColor('#87939D', theme),
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  setColumn: {
    flex: 1,
    color: resolveLegacyColor('#87939D', theme),
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  setKindButton: {
    width: 54,
    minHeight: 52,
    justifyContent: 'center',
  },
  setColumnSmallValue: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 18,
    fontWeight: '900',
    paddingLeft: 4,
  },
  warmupSetKind: {
    color: resolveLegacyColor('#F0B35B', theme),
  },
  failureSetKind: {
    color: resolveLegacyColor('#D84A4A', theme),
  },
  dropSetKind: {
    color: resolveLegacyColor('#7DD3C7', theme),
  },
  setCellInput: {
    flex: 1,
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 18,
    fontWeight: '900',
    minHeight: 52,
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  setColumnValue: {
    flex: 1,
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 18,
    fontWeight: '900',
  },
  completedSetText: {
    color: resolveLegacyColor('#111A1F', theme),
  },
  checkMarkButton: {
    width: 42,
    height: 34,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#E7EAEE', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkMarkDone: {
    backgroundColor: resolveLegacyColor('#33B93B', theme),
  },
  checkMarkText: {
    color: resolveLegacyColor('#A5ADB5', theme),
    fontSize: 22,
    fontWeight: '900',
  },
  checkMarkTextDone: {
    color: resolveLegacyColor('#FFFFFF', theme),
  },
  addSetButton: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#222D35', theme),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  addSetButtonText: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 16,
    fontWeight: '900',
  },
  modalScrim: {
    flex: 1,
    backgroundColor: theme.scrim,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#172027', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    padding: 20,
  },
  editorCard: {
    width: '100%',
    maxHeight: '88%',
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#172027', theme),
  },
  editorContent: {
    padding: 18,
    gap: 12,
  },
  editorLabel: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  editorInput: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#34444F', theme),
    color: resolveLegacyColor('#F7FAFC', theme),
    paddingHorizontal: 14,
    fontSize: 15,
    fontWeight: '700',
  },
  editorTextArea: {
    minHeight: 86,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  exercisePicker: {
    maxHeight: 220,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
  },
  exercisePickRow: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: resolveLegacyColor('#26343E', theme),
  },
  exercisePickName: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontWeight: '800',
    flex: 1,
  },
  emptyText: {
    color: resolveLegacyColor('#9BA8B4', theme),
    padding: 14,
    fontWeight: '700',
  },
  routineEditorBlock: {
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#101820', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    padding: 12,
    gap: 10,
  },
  routineEditorBlockDragging: {
    borderColor: resolveLegacyColor('#7DD3C7', theme),
    backgroundColor: resolveLegacyColor('#16242A', theme),
  },
  routineEditorControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
  },
  routineEditorTitleRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  controlButtonDisabled: {
    opacity: 0.35,
  },
  routineSetEditorRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  routineSetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 4,
  },
  routineSetIndexHeader: {
    width: 42,
    color: resolveLegacyColor('#87939D', theme),
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  routineSetColumnHeader: {
    flex: 1,
    color: resolveLegacyColor('#87939D', theme),
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  routineSetActionHeader: {
    width: 38,
    color: resolveLegacyColor('#87939D', theme),
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  routineSetKindButton: {
    width: 42,
    minHeight: 44,
    justifyContent: 'center',
  },
  routineSetIndex: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 16,
    fontWeight: '900',
  },
  routineSetInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#34444F', theme),
    color: resolveLegacyColor('#F7FAFC', theme),
    paddingHorizontal: 12,
    fontWeight: '800',
  },
  summaryRow: {
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#101820', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  summaryValue: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 16,
    fontWeight: '900',
  },
  smallSquareButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#222D35', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallSquareButtonText: {
    color: resolveLegacyColor('#F0B35B', theme),
    fontSize: 18,
    fontWeight: '900',
  },
  modalTitle: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 22,
    fontWeight: '900',
  },
  modalCopy: {
    color: resolveLegacyColor('#AAB6C1', theme),
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  modalSecondary: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#D9E2DF', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSecondaryText: {
    color: resolveLegacyColor('#111A1F', theme),
    fontWeight: '900',
  },
  modalPrimary: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#F0B35B', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPrimaryText: {
    color: resolveLegacyColor('#16110A', theme),
    fontWeight: '900',
  },
  modalDanger: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#D84A4A', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDangerText: {
    color: resolveLegacyColor('#FFFFFF', theme),
    fontWeight: '900',
  },
  fullWidthDanger: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#D84A4A', theme),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  kindOptions: {
    gap: 8,
    marginTop: 18,
  },
  collectionPickerList: {
    maxHeight: 154,
    marginTop: 12,
  },
  collectionPickerListContent: {
    gap: 8,
  },
  collectionPickerCancel: {
    minHeight: 48,
    width: '100%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  filterRow: {
    gap: 8,
    paddingVertical: 4,
  },
  kindOption: {
    minHeight: 46,
    minWidth: 92,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#D9E2DF', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  kindOptionActive: {
    backgroundColor: theme.primary,
  },
  kindOptionText: {
    color: resolveLegacyColor('#52606A', theme),
    fontWeight: '900',
  },
  kindOptionTextActive: {
    color: theme.onPrimary,
  },
  exerciseList: {
    marginTop: 12,
    gap: 8,
  },
  collectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  routineCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  collectionPickerButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.borderStrong,
    backgroundColor: theme.surfaceElevated,
  },
  collectionAction: {
    color: theme.warning,
    fontSize: 12,
    fontWeight: '900',
  },
  collectionHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  collectionDeleteAction: {
    color: theme.danger,
    fontSize: 12,
    fontWeight: '900',
  },
  routineLine: {
    color: resolveLegacyColor('#D6DEE5', theme),
    fontSize: 14,
  },
  dietMeal: {
    marginTop: 14,
    gap: 7,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  dietChoice: {
    gap: 5,
    padding: 10,
    borderRadius: 8,
    backgroundColor: theme.surfaceElevated,
  },
  dietChoiceLabel: {
    color: theme.warning,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  input: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#34444F', theme),
    color: resolveLegacyColor('#F7FAFC', theme),
    paddingHorizontal: 14,
    fontSize: 15,
  },
  exerciseRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: resolveLegacyColor('#26343E', theme),
    gap: 14,
  },
  exerciseLibraryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  exerciseRowName: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 16,
    fontWeight: '800',
  },
  badge: {
    color: resolveLegacyColor('#F0B35B', theme),
    fontSize: 12,
    fontWeight: '900',
  },
  heroPanel: {
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#172027', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    padding: 18,
    gap: 14,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  iconButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: resolveLegacyColor('#7DD3C7', theme),
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonText: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 12,
    fontWeight: '900',
  },
  bodyProfileRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  collapsibleHeader: {
    minHeight: 48,
  },
  collapsibleContent: {
    flex: 1,
  },
  collapsibleTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  collapsibleTitle: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  weightSummaryRow: {
    minHeight: 86,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 16,
  },
  bigMetric: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 42,
    fontWeight: '900',
  },
  sparkline: {
    flex: 1,
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    gap: 7,
  },
  sparkBar: {
    width: 9,
    borderRadius: 6,
    opacity: 0.95,
  },
  compositionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  bodyMetricCard: {
    width: '48%',
    minHeight: 108,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#101820', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    padding: 12,
    justifyContent: 'space-between',
  },
  bodyMetricValue: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 28,
    fontWeight: '900',
  },
  metricStatus: {
    fontSize: 12,
    fontWeight: '900',
  },
  statusHealthy: {
    color: resolveLegacyColor('#33BFA6', theme),
  },
  statusHigh: {
    color: resolveLegacyColor('#F0B35B', theme),
  },
  statusVeryHigh: {
    color: resolveLegacyColor('#E15D5D', theme),
  },
  statusLow: {
    color: resolveLegacyColor('#8BB8FF', theme),
  },
  statusUnknown: {
    color: resolveLegacyColor('#9BA8B4', theme),
  },
  bmiRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  bmiTrack: {
    height: 8,
    borderRadius: 8,
    marginTop: 18,
    backgroundColor: resolveLegacyColor('#F0B35B', theme),
  },
  bmiMarker: {
    position: 'absolute',
    top: -7,
    width: 22,
    height: 22,
    marginLeft: -11,
    borderRadius: 11,
    backgroundColor: resolveLegacyColor('#7DD3C7', theme),
    borderWidth: 3,
    borderColor: resolveLegacyColor('#172027', theme),
  },
  bmiLabels: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bmiHint: {
    marginTop: 12,
    color: resolveLegacyColor('#F0B35B', theme),
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
  },
  segmentedControl: {
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#101820', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    padding: 4,
    flexDirection: 'row',
    gap: 4,
  },
  profileSegmentButton: {
    flex: 1,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileSegmentButtonActive: {
    backgroundColor: resolveLegacyColor('#7DD3C7', theme),
  },
  profileSegmentButtonText: {
    color: resolveLegacyColor('#9BA8B4', theme),
    fontWeight: '900',
  },
  profileSegmentButtonTextActive: {
    color: resolveLegacyColor('#071313', theme),
  },
  smallActionButton: {
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#222D35', theme),
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  smallActionText: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontWeight: '900',
  },
  photoStrip: {
    gap: 10,
    paddingVertical: 6,
  },
  photoGroups: {
    gap: 14,
  },
  photoFolder: {
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#101820', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    overflow: 'hidden',
  },
  photoFolderHeader: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 12,
  },
  folderIcon: {
    width: 46,
    height: 38,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#223038', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  folderIconText: {
    color: resolveLegacyColor('#F0B35B', theme),
    fontSize: 22,
    fontWeight: '900',
  },
  photoGroup: {
    gap: 6,
  },
  photoGroupTitle: {
    color: resolveLegacyColor('#D6DEE5', theme),
    fontSize: 13,
    fontWeight: '900',
  },
  photoCard: {
    width: 128,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#101820', theme),
    borderWidth: 1,
    borderColor: resolveLegacyColor('#27343D', theme),
    padding: 8,
    gap: 6,
  },
  viewerScrim: {
    flex: 1,
    backgroundColor: 'rgba(5,9,12,0.96)',
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  viewerTopBar: {
    position: 'absolute',
    left: 18,
    right: 18,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  viewerButton: {
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#EAF2EE', theme),
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  viewerButtonText: {
    color: resolveLegacyColor('#111A1F', theme),
    fontWeight: '900',
  },
  viewerDate: {
    color: resolveLegacyColor('#D6DEE5', theme),
    fontWeight: '900',
    flex: 1,
    textAlign: 'right',
  },
  viewerImage: {
    width: '100%',
    flex: 1,
  },
  viewerActions: {
    position: 'absolute',
    left: 18,
    right: 18,
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: 'rgba(17,26,31,0.92)',
    borderWidth: 1,
    borderColor: resolveLegacyColor('#2B3A43', theme),
    padding: 8,
    flexDirection: 'row',
    gap: 10,
  },
  viewerSaveButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#EAF2EE', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewerSaveButtonText: {
    color: resolveLegacyColor('#111A1F', theme),
    fontWeight: '900',
    fontSize: 14,
  },
  viewerDeleteButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#D84A4A', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewerDeleteButtonText: {
    color: resolveLegacyColor('#FFFFFF', theme),
    fontWeight: '900',
    fontSize: 14,
  },
  progressPhoto: {
    width: '100%',
    height: 144,
    borderRadius: 6,
    backgroundColor: resolveLegacyColor('#222D35', theme),
  },
  photoDate: {
    color: resolveLegacyColor('#D6DEE5', theme),
    fontSize: 11,
    fontWeight: '700',
  },
  photoDelete: {
    minHeight: 30,
    borderRadius: 6,
    backgroundColor: resolveLegacyColor('#D84A4A', theme),
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoDeleteText: {
    color: resolveLegacyColor('#FFFFFF', theme),
    fontSize: 11,
    fontWeight: '900',
  },
  bodyHistoryRow: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: resolveLegacyColor('#26343E', theme),
    gap: 12,
  },
  progressRow: {
    minHeight: 46,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: resolveLegacyColor('#26343E', theme),
  },
  progressName: {
    color: resolveLegacyColor('#F7FAFC', theme),
    fontSize: 15,
    fontWeight: '800',
  },
  progressValue: {
    color: resolveLegacyColor('#7DD3C7', theme),
    fontSize: 15,
    fontWeight: '900',
  },
  medal: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    paddingVertical: 10,
  },
  medalIcon: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#F0B35B', theme),
    color: resolveLegacyColor('#16110A', theme),
    fontWeight: '900',
    textAlign: 'center',
    lineHeight: 42,
  },
  medalText: {
    flex: 1,
  },
  tabs: {
    position: 'absolute',
    left: 14,
    right: 14,
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: resolveLegacyColor('#EAF2EE', theme),
    flexDirection: 'row',
    alignItems: 'center',
    padding: 6,
    gap: 6,
  },
  tabButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTab: {
    backgroundColor: theme.onNavigation,
  },
  tabText: {
    color: resolveLegacyColor('#52606A', theme),
    fontSize: 12,
    fontWeight: '900',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  });
}
