import { Dispatch, SetStateAction, useMemo } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAppSettings } from '../../application/AppSettingsContext';
import { EquipmentKind, GripKind, MovementFocus, MuscleGroup } from '../../domain/types';
import { OptionGrid } from '../../ui/FormControls';
import { equipmentLabels, gripLabels, movementLabels, muscleLabels } from '../../ui/labels';
import { ThemeColors } from '../../ui/theme';

export type ExerciseDraft = { id?: string; name: string; muscleGroup: MuscleGroup; equipmentKind: EquipmentKind; equipment: string; grip: GripKind; movementFocus: MovementFocus; notes: string };
const muscleOptions: MuscleGroup[] = ['chest', 'back', 'legs', 'shoulders', 'arms', 'core'];
const equipmentOptions: EquipmentKind[] = ['machine', 'free_weight', 'barbell', 'dumbbell', 'cable', 'bodyweight', 'other'];
const gripOptions: GripKind[] = ['none', 'prone', 'supine', 'neutral', 'mixed'];
const movementOptions: MovementFocus[] = ['none', 'concentric', 'eccentric', 'tempo'];

export function ExerciseEditorModal({ close, deleteExercise, draft, save, setDraft }: { close: () => void; deleteExercise: (exerciseId: string) => void; draft: ExerciseDraft | null; save: () => void; setDraft: Dispatch<SetStateAction<ExerciseDraft | null>> }) {
  const { colors } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]);
  if (!draft) return null;
  const update = <K extends keyof ExerciseDraft>(key: K, value: ExerciseDraft[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  return <Modal transparent animationType="slide" visible onRequestClose={close}><View style={s.scrim}><ScrollView style={s.card} contentContainerStyle={s.content}><Text style={s.title}>{draft.id ? 'Editar ejercicio' : 'Nuevo ejercicio'}</Text><TextInput placeholder="Nombre del ejercicio" placeholderTextColor={colors.textSubtle} style={s.input} value={draft.name} onChangeText={(value) => update('name', value)} /><Text style={s.label}>Grupo muscular</Text><OptionGrid options={muscleOptions} labels={muscleLabels} value={draft.muscleGroup} onChange={(value) => update('muscleGroup', value)} /><Text style={s.label}>Equipo</Text><OptionGrid options={equipmentOptions} labels={equipmentLabels} value={draft.equipmentKind} onChange={(equipmentKind) => setDraft((current) => current ? { ...current, equipmentKind, equipment: current.equipment || equipmentLabels[equipmentKind] } : current)} /><TextInput placeholder="Detalle: máquina, barra, polea..." placeholderTextColor={colors.textSubtle} style={s.input} value={draft.equipment} onChangeText={(value) => update('equipment', value)} /><Text style={s.label}>Agarre opcional</Text><OptionGrid options={gripOptions} labels={gripLabels} value={draft.grip} onChange={(value) => update('grip', value)} /><Text style={s.label}>Foco opcional</Text><OptionGrid options={movementOptions} labels={movementLabels} value={draft.movementFocus} onChange={(value) => update('movementFocus', value)} /><TextInput multiline placeholder="Notas opcionales" placeholderTextColor={colors.textSubtle} style={[s.input, s.textArea]} value={draft.notes} onChangeText={(value) => update('notes', value)} /><View style={s.actions}><Button label="Cancelar" onPress={close} /><Pressable accessibilityRole="button" style={s.primary} onPress={save}><Text style={s.primaryText}>Guardar</Text></Pressable></View>{draft.id && <Pressable accessibilityRole="button" style={s.danger} onPress={() => deleteExercise(draft.id!)}><Text style={s.dangerText}>Eliminar ejercicio</Text></Pressable>}</ScrollView></View></Modal>;
}
function Button({ label, onPress }: { label: string; onPress: () => void }) { const { colors } = useAppSettings(); const s = useMemo(() => createStyles(colors), [colors]); return <Pressable accessibilityRole="button" style={s.secondary} onPress={onPress}><Text style={s.secondaryText}>{label}</Text></Pressable>; }
function createStyles(c: ThemeColors) { return StyleSheet.create({ scrim:{flex:1,backgroundColor:c.scrim,alignItems:'center',justifyContent:'center',padding:20},card:{width:'100%',maxWidth:560,maxHeight:'90%',borderRadius:18,backgroundColor:c.surface},content:{padding:20,gap:14},title:{color:c.text,fontSize:24,fontWeight:'900'},label:{color:c.text,fontSize:13,fontWeight:'800'},input:{minHeight:48,borderRadius:12,borderWidth:1,borderColor:c.borderStrong,color:c.text,paddingHorizontal:14,fontSize:15,fontWeight:'700'},textArea:{minHeight:96,paddingTop:13,textAlignVertical:'top'},actions:{flexDirection:'row',gap:10},secondary:{flex:1,minHeight:48,borderRadius:12,backgroundColor:c.surfaceElevated,alignItems:'center',justifyContent:'center'},secondaryText:{color:c.text,fontWeight:'900'},primary:{flex:1,minHeight:48,borderRadius:12,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},primaryText:{color:c.onPrimary,fontWeight:'900'},danger:{minHeight:48,borderRadius:12,borderWidth:1,borderColor:c.danger,alignItems:'center',justifyContent:'center'},dangerText:{color:c.danger,fontWeight:'900'} }); }
